version: '3.7'

services: 
  next-saas-pg:
    image: bitnami/postgresql:latest
    ports: 
      - 5432:5432
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTEGRESQL_DATABASE=next-saas